service: iera-app-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ca-central-1
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  environment:
    MONGO_URI: ${ssm:/mongo_db}
    SENGRID: ${ssm:/sendgrid}
    PRIVATE_KEY: ${ssm:/private_key}
    PUBLIC_KEY: ${ssm:/public_key}
    R2_ACCESS_ID: ${ssm:/r2_access_id}
    R2_ACCESS_SECRET: ${ssm:/r2_access_secret}
    R2_ENDPOINT: https://b9068f786c3dc33c2c4b3cac9a1638cd.r2.cloudflarestorage.com
    R2_BUCKET: iera-canada-ids
  
functions:
  #open
  login:
    handler: src/users/login.handler
    events:
      - httpApi:
          path: /login
          method: post
  auth:
    handler: src/users/login.auth
    events:
      - httpApi:
          path: /auth
          method: get
  #open
  register:
    handler: src/users/create.handler
    events:
      - httpApi:
          path: /users
          method: post
  #secured, owner, lead, admin TODO
  getUsers:
    handler: src/users/get.handler
    events:
      - httpApi:
          path: /users
          method: get
  getUser:
    handler: src/users/getUser.handler
    events:
      - httpApi:
          path: /users/{user_id}
          method: get
  getUserImage:
    handler: src/users/updateUser.getImage
    events:
      - httpApi:
          path: /users/{user_id}/ids/{image_id}
          method: get
  #secured, owner, lead, admin 
  updateUser:
    handler: src/users/updateUser.handler
    events:
      - httpApi:
          path: /users/{user_id}
          method: put
  #secured, owner
  createRequest:
    handler: src/requests/createRequest.handler
    events:
      - httpApi:
          path: /requests
          method: post
  
  #secured, admin 
  pendingRequests:
    handler: src/requests/getRequests.handler
    events:
      - httpApi:
          path: /requests
          method: get
  
  #secured, admin
  approveRequest:
    handler: src/requests/approveRequest.handler
    events:
      - httpApi:
          path: /requests/{request_id}
          method: put
  

  #secured, owner, lead, admin 
  getTeam:
    handler: src/teams/getTeam.handler
    events:
      - httpApi:
          path: /teams/{team_id}
          method: get
  #secured, owner, lead, admin 
  getTeams:
    handler: src/teams/getTeams.handler
    events:
      - httpApi:
          path: /teams
          method: get
  #secured, admin 
  createTeam:
    handler: src/teams/createTeam.handler
    events:
      - httpApi:
          path: /teams
          method: post
  #secured, admin 
  updateTeam:
    handler: src/teams/updateTeam.handler
    events:
      - httpApi:
          path: /teams/{team_id}
          method: put
  #secured, owner, lead, admin 
  getEvent:
    handler: src/events/getEvent.handler
    events:
      - httpApi:
          path: /teams/{team_id}/events/{event_id}
          method: get
  getEvents:
    handler: src/events/getEvents.handler
    events:
      - httpApi:
          path: /teams/{team_id}/events
          method: get
  getSubEvents:
    handler: src/events/getSubEvents.handler
    events:
      - httpApi:
          path: /teams/{team_id}/sub_events
          method: get
  setSubEventsAttendance:
    handler: src/events/setSubEventAttendance.handler
    events:
      - httpApi:
          path: /teams/{team_id}/sub_events_attendance/{sub_event_id}
          method: put
  deleteSubEventsAttendance:
    handler: src/events/setSubEventAttendance.remove
    events:
      - httpApi:
          path: /teams/{team_id}/sub_events_attendance/{sub_event_id}
          method: delete
  #secured, lead, admin 
  createEvent:
    handler: src/events/createEvent.handler
    events:
      - httpApi:
          path: /teams/{team_id}/events
          method: post
  #secured, lead, admin 
  updateEvent:
    handler: src/events/updateEvent.handler
    events:
      - httpApi:
          path: /teams/{team_id}/events/{event_id}
          method: put
  updateSubEvent:
    handler: src/events/updateSubEvent.handler
    events:
      - httpApi:
          path: /teams/{team_id}/sub_events/{event_id}
          method: put
  getFormTemplate:
    handler: src/forms/forms.getTemplate
    events:
      - httpApi:
          path: /forms/{form_id}
          method: get
  createReport:
    handler: src/reports/report.create
    events:
      - httpApi:
          path: /reports/{type}/{_id}
          method: post
  getReports:
    handler: src/reports/report.gets
    events:
      - httpApi:
          path: /reports/{type}/{_id}
          method: get
  getReport:
    handler: src/reports/report.get
    events:
      - httpApi:
          path: /reports/{type}/{_id}/{report_id}
          method: get
plugins:
  - serverless-offline